# Generated by Django 4.1.1 on 2022-10-05 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.commentmodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postmodel')),
            ],
            options={
                'db_table': 'replycomment',
            },
        ),
    ]
